ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';
DROP TABLE TAREA;
DROP TABLE CONTRATA;
DROP TABLE ALQUILA;
DROP TABLE EQUIPO;
DROP TABLE CONTACTO;
DROP TABLE PROYECTO;

CREATE TABLE PROYECTO(
    NROPROYECTO NUMBER(10) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    FFINALIZACION DATE 
);

CREATE TABLE CONTACTO(
    DOCUMENTO VARCHAR(15) PRIMARY KEY NOT NULL,
    EMAIL VARCHAR (50) UNIQUE NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL,
    TELEFONO VARCHAR (50) NOT NULL,
    TIPO VARCHAR (50) NOT NULL CHECK (TIPO IN ('CLIENTE', 'TECNICO', 'INGENIERO'))
);

CREATE TABLE EQUIPO(
    ID NUMBER(10) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR (50) NOT NULL, 
    ESTADO VARCHAR (50) NOT NULL CHECK (ESTADO IN ('PRODUCCION', 'SERVICE', 'REPARACION', 'DESAFECTADO')),
    FECHAADQUIRIDO DATE NOT NULL,
    CATEGORIA VARCHAR (50) NOT NULL CHECK (CATEGORIA IN ('VIAL', 'CONSTRUCCION', 'HIDRAULICA', 'TERRENO'))
);


CREATE TABLE ALQUILA(
    ID NUMBER(10) REFERENCES EQUIPO(ID) NOT NULL ,
    DOCUMENTO VARCHAR(15) REFERENCES CONTACTO(DOCUMENTO) NOT NULL , 
    FINICIO DATE NOT NULL,
    FFIN DATE,
    PRIMARY KEY (ID, DOCUMENTO, FINICIO)
);

CREATE TABLE CONTRATA(
    NROPROYECTO NUMBER(10) REFERENCES PROYECTO(NROPROYECTO) NOT NULL,
    DOCUMENTO VARCHAR(15) REFERENCES CONTACTO(DOCUMENTO) NOT NULL 
);

CREATE TABLE TAREA(
    NROPROYECTO NUMBER(10) REFERENCES PROYECTO(NROPROYECTO) NOT NULL, 
    IDTAREA NUMBER(10) NOT NULL,
    DESCRIPCION VARCHAR(100) NOT NULL,
    FREALIZACION DATE, 
    PRIMARY KEY (NROPROYECTO, IDTAREA)
);